### PR TITLE
Inteligently determine ElasticSearch Host

### PR DESCRIPTION
**Pull request by d34dh0r53**
If there is an elasticsearch host in the inventory we use the `container_address` for the logstash endpoint, otherwise we use `localhost`.  This also renames `elasticsearch_tcp_port` to `elasticsearch_http_port` and adds the `elasticsearch_tcp_port` which defaults to `9300`.

### CODE REVIEW

**Comment by d34dh0r53** [comment]
recheck_cit_trusty

**Comment by d34dh0r53** [comment]
recheck_cit_trusty_base

**Comment by shannonmitchell** [comment]
The role should be loosely coupled from the inventory and treated like a black box.  I took out the inventory specific variables from the role and moved it over to the playbook in rpc-openstack to allow the reuse of the role in other situations  This allows the role to be used with different inventory layouts and configurations without tying it to OSA. Say if we decide to test out a different inventory system and set of playbooks not related to OSA, you would just have to modify the playbook calling the role without breaking things for OSA or adding a long set of inventory checks in the role.

**Comment by shannonmitchell** [comment]
Example:

https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/logstash.yml

- name: Setup Logstash host
  hosts: logstash_all
  vars:
    - elasticsearch_host: "{{ hostvars[groups['elasticsearch'][0]]['container_address'] }}"
  roles:
    - "rpc-role-logstash"

**Comment by d34dh0r53** [comment]
That's a good point, and it's probably better to do it in the playbooks.

**Comment by shannonmitchell** [comment]
I almost forgot.  Could you put in a PR for the Readme.rst as well to reflect the changes?

**Pull request merged**
