### PR TITLE
RE-1166 Remove legacy .travis.yml file

### PR DESCRIPTION
**Pull request by mattt416**

### CODE REVIEW

**Comment by mattt416** [comment]
This needs to merge _after_ https://github.com/rcbops/rpc-role-logstash/pull/26 merges.

**Comment by hughsaunders** [comment]
rcbops/rpc-gating#611 has merged

**Comment by hughsaunders** [comment]
recheck_all

**Comment by mattt416** [comment]
Updated branch settings to make new container tests required, and the Travis CI test not required.

**Comment by mattt416** [comment]
Don't see an option to "delete" the repo from Travis CI, so just updated the settings to not build if there's no .travis.yml file present.  The same setting is toggled on rpc-openstack.

**Comment by git-harry** [comment]
@mattt416 also https://github.com/rcbops/rpc-role-logstash/settings/installations needs to be updated.

**Pull request merged**
